### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by zacharyweston** [zacharyweston/codelab-external-assets#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://handy-page.surge.sh) and meets the following [project](http://lansingcodelab.com/lessons/external-assets/1) criteria:
- [x] all the styles are in an external `.css` file that have a visible effect on the page
- [x] all the JavaScript is in an external `.js` file, with some behavioral effect on the page
- [x] return no errors (warnings are OK) when the HTML document is uploaded to the [W3C Markup Validation Service](http://validator.w3.org/#validate_by_upload)
- [x] return no errors or warnings when contents of the CSS file are pasted into [CSS Lint](http://csslint.net/)
- [x] return no errors or warnings when the JavaScript is pasted into [JavaScript Lint](http://www.javascriptlint.com/online_lint.php)

**Comment by chrisvfritz** [comment]
Looks great! And I love the use of the `&amp;` [HTML character code](http://rabbit.eng.miami.edu/info/htmlchars.html) for your ampersand. :smiley: 

There's just one little thing that could be improved:

### `script` tags and semantic elements

While I once again really appreciate your consistent use of semantic elements :tada:, I do see one issue here. Since `script` tags aren't strictly _content_, they shouldn't actually be organized within semantic (or other) elements. Instead, it's best to just keep them directly inside the body as the last element(s). In this case, we can simply remove the `aside` element wrapping your `script`. Does that make sense?

<hr>

Also, **is everything working with the Code Lab website now?** I know you were encountering some problems before, so I just want to make sure they're fully resolved!

**Comment by zacharyweston** [comment]
That does make sense, I wasn't sure where they were supposed to fit.  I pushed the updated code to GitHub, and the new URL is guiltless-front.surge.sh

**Comment by zacharyweston** [comment]
Also, for some reason, the lessons do not appear on the Codelab website when I am logged in on Chrome on my WIndows laptop.  I borrowed a Macbook last night, and they appeared fine in Chrome on that.  I will show you what happens during the class session tonight.  I'm going to test visiting the site on my work PC to see what happens there...

**Comment by chrisvfritz** [comment]
:shipit: Beautiful! But sorry to hear you're still experiencing issues on your computer. Something that might be worth trying before tonight is a hard refresh (hold `Ctrl` and click on the refresh button in Chrome). Otherwise, we'll tackle it tonight!
